### ISSUE TITLE
App Name Improvement & Shortening

### ISSUE THREAD

**Issue by sungsphinx** [xverizex/RetroSpriteEditor#10]
https://developer.gnome.org/hig/guidelines/app-naming.html & https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#not-too-long

I was thinking of names like:

- Pixels
- Sprites
- Dots
- Voxels

If you can think of any, please do comment them!

**Comment by xverizex** [comment]
Retro Sprite!
