### ISSUE TITLE
[Feature Request] Use AdwMessageDialog for 'New NES Project' Dialog

### ISSUE THREAD

**Issue by sungsphinx** [xverizex/RetroSpriteEditor#4]
### [AdwMessageDialog Docs](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.MessageDialog.html)

Currently, the dialog looks pretty weird and clunky:
![New NES Project Dialog](https://github.com/xverizex/RetroSpriteEditor/assets/80914457/20de62a1-5b57-4e98-8e45-2ff691d8d124)

The furthest I have got with AdwMessageDialog is:
![AdwMessageDialog](https://github.com/xverizex/RetroSpriteEditor/assets/80914457/f1dd8577-b7b4-4abb-8591-e2cf5e8a3c1a)

Code to show a basic AdwMessageDialog in `main-window.c`:
```
static void
action_new_project_nes (GSimpleAction *simple,
		GVariant *parameter,
		gpointer user_data)
{
	MainWindow *self = MAIN_WINDOW (user_data);
	GtkWidget *dialog;
	//gtk_window_set_transient_for (GTK_WINDOW (self->new_project_nes_window), GTK_WINDOW(self));
	//gtk_window_present (GTK_WINDOW (self->new_project_nes_window));

	const char *heading = "New NES Project";
	const char *body = "Body Text";

	dialog = adw_message_dialog_new (GTK_WINDOW(self), heading, body);
	adw_message_dialog_add_responses (ADW_MESSAGE_DIALOG (dialog),
                                          "cancel", ("Cancel"),
                                          "create", ("Create"),
                                          NULL);
	adw_message_dialog_set_response_appearance (ADW_MESSAGE_DIALOG (dialog), "cancel", ADW_RESPONSE_DESTRUCTIVE);
	//g_signal_connect (dialog, "response", G_CALLBACK (cool_epic_function_here), self);
	gtk_window_present (GTK_WINDOW (dialog));
}
```

You could use [the AdwMessageDialog extra-child property](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/property.MessageDialog.extra-child.html) to add things like text boxes, etc.

Also, setting the dialog window as transient / showing over the main window doesn't work:
![New NES Project Dialog not transient](https://github.com/xverizex/RetroSpriteEditor/assets/80914457/f5f706c9-b8af-4694-b025-d4b393672ad9)

What it should be like:
![About Window which is transient](https://github.com/xverizex/RetroSpriteEditor/assets/80914457/1438a6a4-58fb-40b9-8388-f4c4b024139a)

It should be centered, move the main window with the dialog & not let you focus the main window while the dialog open.

**Comment by xverizex** [comment]
This is cool! This is fits!

**Comment by sungsphinx** [comment]
If the dialog has not been set as transient for the main window automatically, you could try:
```
gtk_window_set_transient_for (GTK_WINDOW (dialog_window_here), GTK_WINDOW(application_window_here));
```

**Comment by xverizex** [comment]
So, have you them doing? Or I will make this feature?

**Comment by sungsphinx** [comment]
I am not sure how to implement the functionality or extra-child stuff, so probably not, maybe you could? (obviously no rush of course)

**Comment by xverizex** [comment]
Of course. I'll take care of it.

**Comment by sungsphinx** [comment]
> Of course. I'll take care of it.

Thanks :+1:

**Comment by xverizex** [comment]
With GTK I work not often, but this fix does the problem. I think the window with parameters is don't dialog in the usual sense. And https://docs.gtk.org/gtk4/class.Dialog.html the dialog is deprecated. I decided leave it as it is and add only modal.
