### ISSUE TITLE
Consider moving from GitHub to FOSS alternatives.

### ISSUE THREAD

**Issue by sungsphinx** [xverizex/RetroSpriteEditor#6]
### Alternatives to GitHub
- **[Forgejo](https://forgejo.org) (Fork of Gitea, [What is unique to Forgejo?](https://forgejo.org/2023-11-release-v1211-0/#what-is-unique-to-forgejo))** (If you don't want to self-host, you can use [Codeberg](https://codeberg.org) and [request CI access](https://codeberg.org/Codeberg-e.V./requests/issues/new?template=ISSUE_TEMPLATE%2fWoodpecker-CI.md) if you wanted to use CI, Forgejo is managed by the community and won't be [taken over by a company](https://gitea-open-letter.coding.social)).

- **[sourcehut](https://sourcehut.org)** (If you don't want to self-host, you can use [sr.ht](https://sr.ht))

- **[GitLab](https://gitlab.com)** (The Official GitLab instance (gitlab.com) requires a credit card for CI access and [**sometimes even for signing up**](https://gitlab.com/librewolf-community/settings/-/issues/265#note_1505029296), GitLab is also owned by a company, and not managed by the community to my knowledge, not a **big** issue though)

- :information_source: Probably more options out there

### Why you should move from GitHub
https://codeberg.org/Recommendations/Mirror_to_Codeberg#why-should-we-mirror-to-codeberg
https://sfconservancy.org/GiveUpGitHub
https://nogithub.codeberg.page
https://github.com/ltGuillaume/LibreWolf-WinUpdater/issues/16
https://github.com/humanetech-community/awesome-humane-tech/issues/33

### If this is too much, or not possible at the moment, consider [setting up mirrors for Codeberg](https://codeberg.org/Recommendations/Mirror_to_Codeberg#github-codeberg-mirroring-tutorial) instead. Thank you for your time!

**Comment by xverizex** [comment]
Oh. I considered your suggestion but have to refuse.

**Comment by xverizex** [comment]
I'm not interested in that.
