### ISSUE TITLE
App Icon which follows the GNOME HIG

### ISSUE THREAD

**Issue by sungsphinx** [xverizex/RetroSpriteEditor#8]
Hi, the current app icon does not really fit the GNOME Human Interface Guidelines, so I have tried to make an icon which hopefully should (also uses GNOME HIG Colors, obviously tell me if you don't like something, I will try to address it):

### Current Prototype
![App Icon Preview Screenshot](https://github.com/xverizex/RetroSpriteEditor/assets/80914457/a20c0fea-1c2b-4289-ab26-80693cc679a7)

### Previous Prototype
![App Icon Preview Screenshot](https://github.com/xverizex/RetroSpriteEditor/assets/80914457/2d1cbb21-8de7-4d7d-866a-d8c32058d99b)

**Comment by xverizex** [comment]
Cool. You are well done! ))

**Comment by xverizex** [comment]
Yes

**Comment by xverizex** [comment]
![image](https://github.com/xverizex/RetroSpriteEditor/assets/21111024/83c24553-cf29-4781-b3e0-449c01516e20)
your case is very dark.
